on: push

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - run: ./build.sh
      - uses: actions/upload-artifact@v3
        with:
          name: basspatch
          path: basspatch
